export const data = {
    activeCustomer: null,
    activeUser: null,
    activeOrder: {
        orderId: null,
        customerId: null,
        isComplete: false,
        inProgress: false,
        date: null
    },
    isGuest: false,
    loginError: false,
    users: [
        {
            id: '001',
            username: 'nyxerus',
            name: 'gabe boley',
            password: '4a7d1ed414474e4033ac29ccb8653d9b',
            phone: '4806284717',
            email: 'gabriel@boley.me',
            avatar: 'daniel.jpg',
            isLoggedIn: false
        },
        {
            id: '002',
            username: 'jsmith',
            name: 'john smith',
            password: 'd93591bdf7860e1e4ee2fca799911215',
            phone: '8014569871',
            email: 'jsmith@gmail.com',
            avatar: 'christian.jpg',
            isLoggedIn: false
        },
        {
            id: '003',
            username: 'aporter',
            name: 'alli porter',
            password: '81dc9bdb52d04dc20036dbd8313ed055',
            phone: '8012448417',
            email: 'aport@gmail.com',
            avatar: 'laura.jpg',
            isLoggedIn: false
        },
        {
            id: '004',
            username: 'lporter',
            name: 'lar porter',
            password: 'd93591bdf7860e1e4ee2fca799911215',
            phone: '8015461234',
            email: 'lporter@gmail.com',
            avatar: 'rachel.png',
            isLoggedIn: false
        },
    ],
    customers: [{
        "id": 1,
        "name": "Flore Parzizek",
        "phone": "1-(775)146-5607",
        "email": "fparzizek0@timesonline.co.uk",
        "dob": "5/2/1971",
        "address": {
            "street1": "181 Crest Line Terrace",
            "street2": null,
            "city": "Carson City",
            "state": "Nevada",
            "country": null
        },
        "acceptSms": true,
        "acceptEmail": false,
        "measurements": {
            "neck": 9,
            "fullChest": 50,
            "fullShoulderWidth": 43,
            "rightSleeve": 49,
            "leftSleeve": 42,
            "bicep": 18,
            "wrist": 1,
            "waist": 41,
            "hips": 29,
            "frontJacketLength": 76,
            "frontChestWidth": 35,
            "backWidth": 24,
            "rightHalfShoulder": 49,
            "leftHalfShoulder": 34,
            "fullBackLength": 60,
            "halfBackLength": 45
        },
        "orders": "ARRAY"
    },
        {
            "id": 2,
            "name": "Luce Kyte",
            "phone": "1-(515)470-0246",
            "email": "lkyte1@sohu.com",
            "dob": "3/26/2000",
            "address": {
                "street1": "7 Little Fleur Place",
                "street2": null,
                "city": "Des Moines",
                "state": "Iowa",
                "country": "USA"
            },
            "acceptSms": false,
            "acceptEmail": true,
            "measurements": {
                "neck": 9,
                "fullChest": 49,
                "fullShoulderWidth": 39,
                "rightSleeve": 39,
                "leftSleeve": 30,
                "bicep": 20,
                "wrist": 8,
                "waist": 13,
                "hips": 22,
                "frontJacketLength": 94,
                "frontChestWidth": 31,
                "backWidth": 41,
                "rightHalfShoulder": 20,
                "leftHalfShoulder": 30,
                "fullBackLength": 26,
                "halfBackLength": 35
            },
            "orders": "ARRAY"
        },
        {
            "id": 3,
            "name": "Joey Satchell",
            "phone": "1-(516)196-5500",
            "email": "jsatchell2@newyorker.com",
            "dob": "8/12/1977",
            "address": {
                "street1": "20166 Emmet Alley",
                "street2": null,
                "city": "Port Washington",
                "state": "New York",
                "country": null
            },
            "acceptSms": false,
            "acceptEmail": true,
            "measurements": {
                "neck": 18,
                "fullChest": 28,
                "fullShoulderWidth": 47,
                "rightSleeve": 46,
                "leftSleeve": 21,
                "bicep": 10,
                "wrist": 5,
                "waist": 14,
                "hips": 43,
                "frontJacketLength": 70,
                "frontChestWidth": 26,
                "backWidth": 25,
                "rightHalfShoulder": 48,
                "leftHalfShoulder": 31,
                "fullBackLength": 42,
                "halfBackLength": 51
            },
            "orders": "ARRAY"
        },
        {
            "id": 970,
            "name": "Yvon Warkup",
            "phone": "1-(405)882-0907",
            "email": "ywarkupqx@npr.org",
            "dob": "2/16/1986",
            "address": {
                "street1": "55 Ilene Road",
                "street2": null,
                "city": "Oklahoma City",
                "state": "Oklahoma",
                "country": null
            },
            "acceptSms": true,
            "acceptEmail": false,
            "measurements": {
                "neck": 20,
                "fullChest": 34,
                "fullShoulderWidth": 29,
                "rightSleeve": 49,
                "leftSleeve": 46,
                "bicep": 11,
                "wrist": 3,
                "waist": 40,
                "hips": 41,
                "frontJacketLength": 61,
                "frontChestWidth": 45,
                "backWidth": 52,
                "rightHalfShoulder": 41,
                "leftHalfShoulder": 43,
                "fullBackLength": 35,
                "halfBackLength": 56
            },
            "orders": "ARRAY"
        },
        {
            "id": 971,
            "name": "Tonnie Gallico",
            "phone": "1-(214)231-6566",
            "email": "tgallicoqy@illinois.edu",
            "dob": "7/28/1977",
            "address": {
                "street1": "37184 Charing Cross Pass",
                "street2": null,
                "city": "Dallas",
                "state": "Texas",
                "country": null
            },
            "acceptSms": false,
            "acceptEmail": true,
            "measurements": {
                "neck": 20,
                "fullChest": 31,
                "fullShoulderWidth": 39,
                "rightSleeve": 43,
                "leftSleeve": 34,
                "bicep": 13,
                "wrist": 6,
                "waist": 41,
                "hips": 23,
                "frontJacketLength": 55,
                "frontChestWidth": 50,
                "backWidth": 44,
                "rightHalfShoulder": 56,
                "leftHalfShoulder": 31,
                "fullBackLength": 32,
                "halfBackLength": 21
            },
            "orders": "ARRAY"
        },
        {
            "id": 972,
            "name": "Arlena Filon",
            "phone": "1-(775)570-6661",
            "email": "afilonqz@miitbeian.gov.cn",
            "dob": "4/18/1967",
            "address": {
                "street1": "7 Swallow Plaza",
                "street2": null,
                "city": "Reno",
                "state": "Nevada",
                "country": null
            },
            "acceptSms": false,
            "acceptEmail": false,
            "measurements": {
                "neck": 14,
                "fullChest": 37,
                "fullShoulderWidth": 50,
                "rightSleeve": 37,
                "leftSleeve": 41,
                "bicep": 19,
                "wrist": 8,
                "waist": 23,
                "hips": 26,
                "frontJacketLength": 62,
                "frontChestWidth": 46,
                "backWidth": 52,
                "rightHalfShoulder": 44,
                "leftHalfShoulder": 55,
                "fullBackLength": 40,
                "halfBackLength": 49
            },
            "orders": "ARRAY"
        },
        {
            "id": 973,
            "name": "Rafa Pledger",
            "phone": "1-(843)420-1548",
            "email": "rpledgerr0@berkeley.edu",
            "dob": "2/25/1992",
            "address": {
                "street1": "2203 Dottie Way",
                "street2": "24728 Mcguire Park",
                "city": "Beaufort",
                "state": "South Carolina",
                "country": null
            },
            "acceptSms": false,
            "acceptEmail": true,
            "measurements": {
                "neck": 20,
                "fullChest": 48,
                "fullShoulderWidth": 40,
                "rightSleeve": 35,
                "leftSleeve": 38,
                "bicep": 13,
                "wrist": 7,
                "waist": 32,
                "hips": 45,
                "frontJacketLength": 56,
                "frontChestWidth": 39,
                "backWidth": 42,
                "rightHalfShoulder": 31,
                "leftHalfShoulder": 41,
                "fullBackLength": 57,
                "halfBackLength": 55
            },
            "orders": "ARRAY"
        },
        {
            "id": 974,
            "name": "Sarge Beckingham",
            "phone": "1-(601)674-8479",
            "email": "sbeckinghamr1@house.gov",
            "dob": "8/28/1978",
            "address": {
                "street1": "8349 Buena Vista Center",
                "street2": null,
                "city": "Jackson",
                "state": "Mississippi",
                "country": "USA"
            },
            "acceptSms": true,
            "acceptEmail": true,
            "measurements": {
                "neck": 9,
                "fullChest": 20,
                "fullShoulderWidth": 50,
                "rightSleeve": 40,
                "leftSleeve": 43,
                "bicep": 15,
                "wrist": 2,
                "waist": 36,
                "hips": 37,
                "frontJacketLength": 62,
                "frontChestWidth": 37,
                "backWidth": 21,
                "rightHalfShoulder": 41,
                "leftHalfShoulder": 35,
                "fullBackLength": 25,
                "halfBackLength": 55
            },
            "orders": "ARRAY"
        },
        {
            "id": 975,
            "name": "Maryjo Lambdin",
            "phone": "1-(212)117-2658",
            "email": "mlambdinr2@bluehost.com",
            "dob": "4/21/1958",
            "address": {
                "street1": "0 Messerschmidt Court",
                "street2": null,
                "city": "New York City",
                "state": "New York",
                "country": "USA"
            },
            "acceptSms": true,
            "acceptEmail": false,
            "measurements": {
                "neck": 9,
                "fullChest": 32,
                "fullShoulderWidth": 50,
                "rightSleeve": 47,
                "leftSleeve": 42,
                "bicep": 18,
                "wrist": 5,
                "waist": 28,
                "hips": 46,
                "frontJacketLength": 59,
                "frontChestWidth": 24,
                "backWidth": 42,
                "rightHalfShoulder": 46,
                "leftHalfShoulder": 60,
                "fullBackLength": 41,
                "halfBackLength": 60
            },
            "orders": "ARRAY"
        },
        {
            "id": 976,
            "name": "Marleen Rankmore",
            "phone": "1-(404)516-5358",
            "email": "mrankmorer3@skyrock.com",
            "dob": "1/15/1962",
            "address": {
                "street1": "20 Onsgard Point",
                "street2": null,
                "city": "Atlanta",
                "state": "Georgia",
                "country": "USA"
            },
            "acceptSms": true,
            "acceptEmail": true,
            "measurements": {
                "neck": 9,
                "fullChest": 33,
                "fullShoulderWidth": 34,
                "rightSleeve": 30,
                "leftSleeve": 38,
                "bicep": 14,
                "wrist": 8,
                "waist": 32,
                "hips": 45,
                "frontJacketLength": 44,
                "frontChestWidth": 45,
                "backWidth": 42,
                "rightHalfShoulder": 54,
                "leftHalfShoulder": 30,
                "fullBackLength": 57,
                "halfBackLength": 40
            },
            "orders": "ARRAY"
        },
        {
            "id": 977,
            "name": "Dwight Hollow",
            "phone": "1-(732)785-5432",
            "email": "dhollowr4@fastcompany.com",
            "dob": "3/27/1964",
            "address": {
                "street1": "35679 Elka Junction",
                "street2": null,
                "city": "New Brunswick",
                "state": "New Jersey",
                "country": "USA"
            },
            "acceptSms": false,
            "acceptEmail": true,
            "measurements": {
                "neck": 12,
                "fullChest": 50,
                "fullShoulderWidth": 38,
                "rightSleeve": 33,
                "leftSleeve": 43,
                "bicep": 10,
                "wrist": 5,
                "waist": 26,
                "hips": 47,
                "frontJacketLength": 37,
                "frontChestWidth": 28,
                "backWidth": 35,
                "rightHalfShoulder": 43,
                "leftHalfShoulder": 20,
                "fullBackLength": 26,
                "halfBackLength": 60
            },
            "orders": "ARRAY"
        },
        {
            "id": 978,
            "name": "Dorian Undrell",
            "phone": "1-(504)281-0287",
            "email": "dundrellr5@seesaa.net",
            "dob": "2/13/1998",
            "address": {
                "street1": "3577 Russell Lane",
                "street2": null,
                "city": "New Orleans",
                "state": "Louisiana",
                "country": "USA"
            },
            "acceptSms": false,
            "acceptEmail": false,
            "measurements": {
                "neck": 17,
                "fullChest": 39,
                "fullShoulderWidth": 33,
                "rightSleeve": 31,
                "leftSleeve": 43,
                "bicep": 19,
                "wrist": 5,
                "waist": 33,
                "hips": 34,
                "frontJacketLength": 60,
                "frontChestWidth": 52,
                "backWidth": 21,
                "rightHalfShoulder": 25,
                "leftHalfShoulder": 20,
                "fullBackLength": 21,
                "halfBackLength": 46
            },
            "orders": "ARRAY"
        },
        {
            "id": 979,
            "name": "Nicolai Flamank",
            "phone": "1-(203)432-1179",
            "email": "nflamankr6@pen.io",
            "dob": "9/27/1999",
            "address": {
                "street1": "15150 Clyde Gallagher Court",
                "street2": null,
                "city": "New Haven",
                "state": "Connecticut",
                "country": "USA"
            },
            "acceptSms": true,
            "acceptEmail": true,
            "measurements": {
                "neck": 8,
                "fullChest": 27,
                "fullShoulderWidth": 31,
                "rightSleeve": 21,
                "leftSleeve": 43,
                "bicep": 13,
                "wrist": 8,
                "waist": 40,
                "hips": 27,
                "frontJacketLength": 48,
                "frontChestWidth": 26,
                "backWidth": 48,
                "rightHalfShoulder": 60,
                "leftHalfShoulder": 34,
                "fullBackLength": 60,
                "halfBackLength": 24
            },
            "orders": "ARRAY"
        },
        {
            "id": 980,
            "name": "Mariette Hargreaves",
            "phone": "1-(719)217-2802",
            "email": "mhargreavesr7@phpbb.com",
            "dob": "8/5/1971",
            "address": {
                "street1": "40637 Sunbrook Trail",
                "street2": null,
                "city": "Colorado Springs",
                "state": "Colorado",
                "country": "USA"
            },
            "acceptSms": true,
            "acceptEmail": false,
            "measurements": {
                "neck": 10,
                "fullChest": 21,
                "fullShoulderWidth": 25,
                "rightSleeve": 37,
                "leftSleeve": 26,
                "bicep": 19,
                "wrist": 3,
                "waist": 37,
                "hips": 17,
                "frontJacketLength": 89,
                "frontChestWidth": 52,
                "backWidth": 54,
                "rightHalfShoulder": 46,
                "leftHalfShoulder": 33,
                "fullBackLength": 30,
                "halfBackLength": 53
            },
            "orders": "ARRAY"
        },
        {
            "id": 981,
            "name": "Merwyn MacNab",
            "phone": "1-(713)377-9592",
            "email": "mmacnabr8@nbcnews.com",
            "dob": "1/31/1964",
            "address": {
                "street1": "20 Summit Parkway",
                "street2": "0680 Rockefeller Alley",
                "city": "Houston",
                "state": "Texas",
                "country": null
            },
            "acceptSms": false,
            "acceptEmail": false,
            "measurements": {
                "neck": 12,
                "fullChest": 40,
                "fullShoulderWidth": 29,
                "rightSleeve": 30,
                "leftSleeve": 47,
                "bicep": 13,
                "wrist": 1,
                "waist": 44,
                "hips": 48,
                "frontJacketLength": 39,
                "frontChestWidth": 27,
                "backWidth": 28,
                "rightHalfShoulder": 24,
                "leftHalfShoulder": 46,
                "fullBackLength": 36,
                "halfBackLength": 45
            },
            "orders": "ARRAY"
        },
        {
            "id": 982,
            "name": "Myrtie Earngy",
            "phone": "1-(970)409-6276",
            "email": "mearngyr9@lycos.com",
            "dob": "11/16/1991",
            "address": {
                "street1": "56808 Glacier Hill Circle",
                "street2": null,
                "city": "Greeley",
                "state": "Colorado",
                "country": null
            },
            "acceptSms": false,
            "acceptEmail": true,
            "measurements": {
                "neck": 19,
                "fullChest": 43,
                "fullShoulderWidth": 31,
                "rightSleeve": 46,
                "leftSleeve": 21,
                "bicep": 13,
                "wrist": 3,
                "waist": 13,
                "hips": 27,
                "frontJacketLength": 69,
                "frontChestWidth": 25,
                "backWidth": 59,
                "rightHalfShoulder": 56,
                "leftHalfShoulder": 42,
                "fullBackLength": 34,
                "halfBackLength": 21
            },
            "orders": "ARRAY"
        },
        {
            "id": 983,
            "name": "Marven Cholonin",
            "phone": "1-(402)436-9042",
            "email": "mcholoninra@squidoo.com",
            "dob": "8/17/1989",
            "address": {
                "street1": "39 Manufacturers Circle",
                "street2": "32923 Little Fleur Alley",
                "city": "Lincoln",
                "state": "Nebraska",
                "country": null
            },
            "acceptSms": false,
            "acceptEmail": true,
            "measurements": {
                "neck": 10,
                "fullChest": 37,
                "fullShoulderWidth": 22,
                "rightSleeve": 27,
                "leftSleeve": 50,
                "bicep": 16,
                "wrist": 6,
                "waist": 37,
                "hips": 13,
                "frontJacketLength": 45,
                "frontChestWidth": 52,
                "backWidth": 30,
                "rightHalfShoulder": 35,
                "leftHalfShoulder": 60,
                "fullBackLength": 34,
                "halfBackLength": 23
            },
            "orders": "ARRAY"
        },
        {
            "id": 984,
            "name": "Jammie Rodie",
            "phone": "1-(618)880-1922",
            "email": "jrodierb@examiner.com",
            "dob": "5/27/1970",
            "address": {
                "street1": "91584 Village Green Park",
                "street2": null,
                "city": "East Saint Louis",
                "state": "Illinois",
                "country": null
            },
            "acceptSms": false,
            "acceptEmail": true,
            "measurements": {
                "neck": 10,
                "fullChest": 30,
                "fullShoulderWidth": 36,
                "rightSleeve": 43,
                "leftSleeve": 20,
                "bicep": 20,
                "wrist": 7,
                "waist": 47,
                "hips": 47,
                "frontJacketLength": 39,
                "frontChestWidth": 41,
                "backWidth": 27,
                "rightHalfShoulder": 43,
                "leftHalfShoulder": 37,
                "fullBackLength": 57,
                "halfBackLength": 54
            },
            "orders": "ARRAY"
        },
        {
            "id": 985,
            "name": "Dina Stirrup",
            "phone": "1-(862)435-0063",
            "email": "dstirruprc@desdev.cn",
            "dob": "12/19/1984",
            "address": {
                "street1": "622 Lunder Drive",
                "street2": null,
                "city": "Paterson",
                "state": "New Jersey",
                "country": "USA"
            },
            "acceptSms": false,
            "acceptEmail": true,
            "measurements": {
                "neck": 19,
                "fullChest": 48,
                "fullShoulderWidth": 30,
                "rightSleeve": 30,
                "leftSleeve": 33,
                "bicep": 10,
                "wrist": 8,
                "waist": 26,
                "hips": 34,
                "frontJacketLength": 74,
                "frontChestWidth": 22,
                "backWidth": 20,
                "rightHalfShoulder": 37,
                "leftHalfShoulder": 51,
                "fullBackLength": 57,
                "halfBackLength": 56
            },
            "orders": "ARRAY"
        },
        {
            "id": 986,
            "name": "Georgeta Menauteau",
            "phone": "1-(808)425-5660",
            "email": "gmenauteaurd@china.com.cn",
            "dob": "10/20/1982",
            "address": {
                "street1": "94581 Namekagon Drive",
                "street2": null,
                "city": "Honolulu",
                "state": "Hawaii",
                "country": null
            },
            "acceptSms": false,
            "acceptEmail": false,
            "measurements": {
                "neck": 10,
                "fullChest": 44,
                "fullShoulderWidth": 45,
                "rightSleeve": 34,
                "leftSleeve": 40,
                "bicep": 14,
                "wrist": 4,
                "waist": 41,
                "hips": 49,
                "frontJacketLength": 79,
                "frontChestWidth": 55,
                "backWidth": 50,
                "rightHalfShoulder": 36,
                "leftHalfShoulder": 55,
                "fullBackLength": 42,
                "halfBackLength": 48
            },
            "orders": "ARRAY"
        },
        {
            "id": 987,
            "name": "Genny Maps",
            "phone": "1-(918)833-8765",
            "email": "gmapsre@nydailynews.com",
            "dob": "5/8/1969",
            "address": {
                "street1": "830 Forest Crossing",
                "street2": null,
                "city": "Tulsa",
                "state": "Oklahoma",
                "country": "USA"
            },
            "acceptSms": true,
            "acceptEmail": false,
            "measurements": {
                "neck": 18,
                "fullChest": 37,
                "fullShoulderWidth": 48,
                "rightSleeve": 49,
                "leftSleeve": 47,
                "bicep": 11,
                "wrist": 1,
                "waist": 38,
                "hips": 46,
                "frontJacketLength": 96,
                "frontChestWidth": 25,
                "backWidth": 42,
                "rightHalfShoulder": 49,
                "leftHalfShoulder": 32,
                "fullBackLength": 22,
                "halfBackLength": 56
            },
            "orders": "ARRAY"
        },
        {
            "id": 988,
            "name": "Redd Wilflinger",
            "phone": "1-(305)643-8418",
            "email": "rwilflingerrf@typepad.com",
            "dob": "5/5/1976",
            "address": {
                "street1": "5 Vermont Trail",
                "street2": null,
                "city": "Naples",
                "state": "Florida",
                "country": null
            },
            "acceptSms": true,
            "acceptEmail": true,
            "measurements": {
                "neck": 16,
                "fullChest": 33,
                "fullShoulderWidth": 33,
                "rightSleeve": 23,
                "leftSleeve": 46,
                "bicep": 18,
                "wrist": 8,
                "waist": 41,
                "hips": 50,
                "frontJacketLength": 41,
                "frontChestWidth": 39,
                "backWidth": 28,
                "rightHalfShoulder": 34,
                "leftHalfShoulder": 35,
                "fullBackLength": 50,
                "halfBackLength": 27
            },
            "orders": "ARRAY"
        },
        {
            "id": 989,
            "name": "Josephine Fike",
            "phone": "1-(585)107-3731",
            "email": "jfikerg@51.la",
            "dob": "3/2/1975",
            "address": {
                "street1": "13612 Evergreen Drive",
                "street2": null,
                "city": "Rochester",
                "state": "New York",
                "country": null
            },
            "acceptSms": true,
            "acceptEmail": true,
            "measurements": {
                "neck": 12,
                "fullChest": 32,
                "fullShoulderWidth": 49,
                "rightSleeve": 43,
                "leftSleeve": 23,
                "bicep": 20,
                "wrist": 2,
                "waist": 11,
                "hips": 39,
                "frontJacketLength": 94,
                "frontChestWidth": 37,
                "backWidth": 48,
                "rightHalfShoulder": 49,
                "leftHalfShoulder": 39,
                "fullBackLength": 54,
                "halfBackLength": 40
            },
            "orders": "ARRAY"
        },
        {
            "id": 990,
            "name": "Lanna McCleod",
            "phone": "1-(714)511-9982",
            "email": "lmccleodrh@guardian.co.uk",
            "dob": "8/30/1976",
            "address": {
                "street1": "11588 Stone Corner Court",
                "street2": null,
                "city": "Garden Grove",
                "state": "California",
                "country": null
            },
            "acceptSms": true,
            "acceptEmail": true,
            "measurements": {
                "neck": 16,
                "fullChest": 39,
                "fullShoulderWidth": 22,
                "rightSleeve": 23,
                "leftSleeve": 33,
                "bicep": 15,
                "wrist": 5,
                "waist": 46,
                "hips": 47,
                "frontJacketLength": 57,
                "frontChestWidth": 26,
                "backWidth": 29,
                "rightHalfShoulder": 40,
                "leftHalfShoulder": 46,
                "fullBackLength": 58,
                "halfBackLength": 56
            },
            "orders": "ARRAY"
        },
        {
            "id": 991,
            "name": "Hilliard Chattaway",
            "phone": "1-(518)354-2061",
            "email": "hchattawayri@exblog.jp",
            "dob": "11/18/1993",
            "address": {
                "street1": "352 Tomscot Trail",
                "street2": null,
                "city": "Schenectady",
                "state": "New York",
                "country": null
            },
            "acceptSms": true,
            "acceptEmail": true,
            "measurements": {
                "neck": 13,
                "fullChest": 30,
                "fullShoulderWidth": 45,
                "rightSleeve": 31,
                "leftSleeve": 47,
                "bicep": 13,
                "wrist": 5,
                "waist": 40,
                "hips": 10,
                "frontJacketLength": 94,
                "frontChestWidth": 40,
                "backWidth": 31,
                "rightHalfShoulder": 24,
                "leftHalfShoulder": 37,
                "fullBackLength": 25,
                "halfBackLength": 45
            },
            "orders": "ARRAY"
        },
        {
            "id": 992,
            "name": "Brynne Markey",
            "phone": "1-(702)904-0015",
            "email": "bmarkeyrj@spotify.com",
            "dob": "11/22/1959",
            "address": {
                "street1": "7204 Dryden Pass",
                "street2": null,
                "city": "Las Vegas",
                "state": "Nevada",
                "country": null
            },
            "acceptSms": true,
            "acceptEmail": false,
            "measurements": {
                "neck": 14,
                "fullChest": 23,
                "fullShoulderWidth": 21,
                "rightSleeve": 45,
                "leftSleeve": 20,
                "bicep": 11,
                "wrist": 3,
                "waist": 23,
                "hips": 25,
                "frontJacketLength": 55,
                "frontChestWidth": 29,
                "backWidth": 38,
                "rightHalfShoulder": 43,
                "leftHalfShoulder": 57,
                "fullBackLength": 57,
                "halfBackLength": 46
            },
            "orders": "ARRAY"
        },
        {
            "id": 993,
            "name": "Isaak Doorey",
            "phone": "1-(561)513-6169",
            "email": "idooreyrk@hexun.com",
            "dob": "11/7/1978",
            "address": {
                "street1": "1381 Sherman Pass",
                "street2": null,
                "city": "West Palm Beach",
                "state": "Florida",
                "country": null
            },
            "acceptSms": false,
            "acceptEmail": true,
            "measurements": {
                "neck": 12,
                "fullChest": 47,
                "fullShoulderWidth": 47,
                "rightSleeve": 25,
                "leftSleeve": 32,
                "bicep": 13,
                "wrist": 2,
                "waist": 29,
                "hips": 37,
                "frontJacketLength": 97,
                "frontChestWidth": 56,
                "backWidth": 50,
                "rightHalfShoulder": 54,
                "leftHalfShoulder": 60,
                "fullBackLength": 56,
                "halfBackLength": 56
            },
            "orders": "ARRAY"
        },
        {
            "id": 994,
            "name": "Christopher Kadwallider",
            "phone": "1-(563)722-0261",
            "email": "ckadwalliderrl@360.cn",
            "dob": "5/27/1991",
            "address": {
                "street1": "440 Maryland Lane",
                "street2": null,
                "city": "Davenport",
                "state": "Iowa",
                "country": "USA"
            },
            "acceptSms": true,
            "acceptEmail": false,
            "measurements": {
                "neck": 9,
                "fullChest": 45,
                "fullShoulderWidth": 43,
                "rightSleeve": 35,
                "leftSleeve": 44,
                "bicep": 14,
                "wrist": 3,
                "waist": 42,
                "hips": 14,
                "frontJacketLength": 44,
                "frontChestWidth": 51,
                "backWidth": 22,
                "rightHalfShoulder": 46,
                "leftHalfShoulder": 25,
                "fullBackLength": 24,
                "halfBackLength": 58
            },
            "orders": "ARRAY"
        },
        {
            "id": 995,
            "name": "Wayne Falcus",
            "phone": "1-(239)976-2158",
            "email": "wfalcusrm@soundcloud.com",
            "dob": "12/3/1963",
            "address": {
                "street1": "6 American Ash Way",
                "street2": "74909 Roxbury Park",
                "city": "Fort Myers",
                "state": "Florida",
                "country": null
            },
            "acceptSms": false,
            "acceptEmail": true,
            "measurements": {
                "neck": 13,
                "fullChest": 31,
                "fullShoulderWidth": 25,
                "rightSleeve": 27,
                "leftSleeve": 44,
                "bicep": 16,
                "wrist": 1,
                "waist": 21,
                "hips": 10,
                "frontJacketLength": 71,
                "frontChestWidth": 28,
                "backWidth": 20,
                "rightHalfShoulder": 24,
                "leftHalfShoulder": 28,
                "fullBackLength": 40,
                "halfBackLength": 60
            },
            "orders": "ARRAY"
        },
        {
            "id": 996,
            "name": "Viviene Gilvary",
            "phone": "1-(202)114-8533",
            "email": "vgilvaryrn@bandcamp.com",
            "dob": "7/16/1992",
            "address": {
                "street1": "7990 Nevada Avenue",
                "street2": null,
                "city": "Washington",
                "state": "District of Columbia",
                "country": "USA"
            },
            "acceptSms": false,
            "acceptEmail": true,
            "measurements": {
                "neck": 11,
                "fullChest": 44,
                "fullShoulderWidth": 48,
                "rightSleeve": 36,
                "leftSleeve": 40,
                "bicep": 17,
                "wrist": 3,
                "waist": 23,
                "hips": 33,
                "frontJacketLength": 32,
                "frontChestWidth": 40,
                "backWidth": 40,
                "rightHalfShoulder": 27,
                "leftHalfShoulder": 51,
                "fullBackLength": 56,
                "halfBackLength": 55
            },
            "orders": "ARRAY"
        },
        {
            "id": 997,
            "name": "Mallissa Perez",
            "phone": "1-(850)136-8634",
            "email": "mperezro@wired.com",
            "dob": "10/7/1996",
            "address": {
                "street1": "7216 Rusk Plaza",
                "street2": "64497 Heffernan Terrace",
                "city": "Pinellas Park",
                "state": "Florida",
                "country": null
            },
            "acceptSms": false,
            "acceptEmail": true,
            "measurements": {
                "neck": 20,
                "fullChest": 48,
                "fullShoulderWidth": 35,
                "rightSleeve": 20,
                "leftSleeve": 22,
                "bicep": 18,
                "wrist": 7,
                "waist": 35,
                "hips": 32,
                "frontJacketLength": 89,
                "frontChestWidth": 54,
                "backWidth": 59,
                "rightHalfShoulder": 28,
                "leftHalfShoulder": 56,
                "fullBackLength": 33,
                "halfBackLength": 60
            },
            "orders": "ARRAY"
        },
        {
            "id": 998,
            "name": "Delcine Grouvel",
            "phone": "1-(310)664-1068",
            "email": "dgrouvelrp@washingtonpost.com",
            "dob": "8/6/1952",
            "address": {
                "street1": "1818 Browning Way",
                "street2": null,
                "city": "Inglewood",
                "state": "California",
                "country": null
            },
            "acceptSms": false,
            "acceptEmail": true,
            "measurements": {
                "neck": 9,
                "fullChest": 45,
                "fullShoulderWidth": 39,
                "rightSleeve": 41,
                "leftSleeve": 42,
                "bicep": 12,
                "wrist": 4,
                "waist": 19,
                "hips": 48,
                "frontJacketLength": 99,
                "frontChestWidth": 48,
                "backWidth": 39,
                "rightHalfShoulder": 59,
                "leftHalfShoulder": 26,
                "fullBackLength": 57,
                "halfBackLength": 41
            },
            "orders": "ARRAY"
        },
        {
            "id": 999,
            "name": "Aloysius Gable",
            "phone": "1-(213)409-7497",
            "email": "agablerq@purevolume.com",
            "dob": "5/6/1979",
            "address": {
                "street1": "57412 Jenifer Circle",
                "street2": null,
                "city": "Los Angeles",
                "state": "California",
                "country": "USA"
            },
            "acceptSms": true,
            "acceptEmail": false,
            "measurements": {
                "neck": 17,
                "fullChest": 30,
                "fullShoulderWidth": 37,
                "rightSleeve": 22,
                "leftSleeve": 29,
                "bicep": 10,
                "wrist": 6,
                "waist": 32,
                "hips": 50,
                "frontJacketLength": 63,
                "frontChestWidth": 60,
                "backWidth": 57,
                "rightHalfShoulder": 36,
                "leftHalfShoulder": 41,
                "fullBackLength": 29,
                "halfBackLength": 41
            },
            "orders": "ARRAY"
        },
        {
            "id": 1000,
            "name": "Gaston Dowdell",
            "phone": "1-(601)947-1773",
            "email": "gdowdellrr@purevolume.com",
            "dob": "5/20/1979",
            "address": {
                "street1": "7 Becker Crossing",
                "street2": null,
                "city": "Jackson",
                "state": "Mississippi",
                "country": null
            },
            "acceptSms": true,
            "acceptEmail": false,
            "measurements": {
                "neck": 20,
                "fullChest": 31,
                "fullShoulderWidth": 37,
                "rightSleeve": 22,
                "leftSleeve": 47,
                "bicep": 15,
                "wrist": 2,
                "waist": 21,
                "hips": 15,
                "frontJacketLength": 44,
                "frontChestWidth": 26,
                "backWidth": 21,
                "rightHalfShoulder": 35,
                "leftHalfShoulder": 29,
                "fullBackLength": 33,
                "halfBackLength": 51
            },
            "orders": "ARRAY"
        }],
    products: [{
        "id": 1,
        "name": "Vagram",
        "description": null,
        "canBeAltered": false,
        "canBeShipped": true,
        "price": "$5932.13",
        "images": "IMAGE_ARRAY",
        "notes": null,
        "garmentType": "slacks",
        "quantity": 49,
        "measurementType": null
    },
        {
            "id": 25,
            "name": "Fixflex",
            "description": "cras pellentesque volutpat dui maecenas tristique est et tempus semper",
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$3230.57",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "suit",
            "quantity": 74,
            "measurementType": null
        },
        {
            "id": 26,
            "name": "Tresom",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$153.81",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "slacks",
            "quantity": 40,
            "measurementType": null
        },
        {
            "id": 27,
            "name": "Zaam-Dox",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$1214.20",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sportswear",
            "quantity": 44,
            "measurementType": null
        },
        {
            "id": 28,
            "name": "Otcom",
            "description": "sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat",
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$3715.76",
            "images": "IMAGE_ARRAY",
            "notes": "id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet",
            "garmentType": null,
            "quantity": 10,
            "measurementType": "custom"
        },
        {
            "id": 29,
            "name": "Zamit",
            "description": "id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque",
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$781.54",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": null,
            "quantity": 29,
            "measurementType": null
        },
        {
            "id": 30,
            "name": "Alpha",
            "description": "quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis",
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$3356.43",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": null,
            "quantity": 73,
            "measurementType": null
        },
        {
            "id": 31,
            "name": "Cardify",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$5636.46",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "slacks",
            "quantity": 3,
            "measurementType": null
        },
        {
            "id": 32,
            "name": "Vagram",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$5527.93",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "formal wear",
            "quantity": 78,
            "measurementType": null
        },
        {
            "id": 33,
            "name": "Rank",
            "description": "donec vitae nisi nam ultrices libero non mattis pulvinar nulla",
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$2963.15",
            "images": "IMAGE_ARRAY",
            "notes": "cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus",
            "garmentType": "slacks",
            "quantity": 4,
            "measurementType": "custom"
        },
        {
            "id": 34,
            "name": "Duobam",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$5417.86",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "formal wear",
            "quantity": 17,
            "measurementType": null
        },
        {
            "id": 35,
            "name": "Regrant",
            "description": "feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa",
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$5303.66",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "suit",
            "quantity": 44,
            "measurementType": null
        },
        {
            "id": 36,
            "name": "Job",
            "description": "sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum",
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$5094.51",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "outerwear",
            "quantity": 32,
            "measurementType": null
        },
        {
            "id": 37,
            "name": "Vagram",
            "description": "mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula",
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$1082.95",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "outerwear",
            "quantity": 51,
            "measurementType": null
        },
        {
            "id": 38,
            "name": "Alphazap",
            "description": "nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque",
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$5488.95",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "accessories",
            "quantity": 64,
            "measurementType": null
        },
        {
            "id": 39,
            "name": "Flexidy",
            "description": "orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio",
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$3575.73",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "accessories",
            "quantity": 96,
            "measurementType": null
        },
        {
            "id": 40,
            "name": "Cardguard",
            "description": "ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat",
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$1957.52",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "shoes",
            "quantity": 5,
            "measurementType": null
        },
        {
            "id": 41,
            "name": "Voyatouch",
            "description": "ultrices libero non mattis pulvinar nulla pede ullamcorper augue a",
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$5967.51",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sportswear",
            "quantity": 13,
            "measurementType": null
        },
        {
            "id": 42,
            "name": "Job",
            "description": "pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc",
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$5086.96",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "slacks",
            "quantity": 54,
            "measurementType": null
        },
        {
            "id": 43,
            "name": "Wrapsafe",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$3129.15",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "slacks",
            "quantity": 61,
            "measurementType": null
        },
        {
            "id": 44,
            "name": "Prodder",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": true,
            "price": "$4177.59",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "accessories",
            "quantity": 65,
            "measurementType": null
        },
        {
            "id": 45,
            "name": "Regrant",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$683.36",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "shoes",
            "quantity": 62,
            "measurementType": null
        },
        {
            "id": 46,
            "name": "Redhold",
            "description": "sapien non mi integer ac neque duis bibendum morbi non quam",
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$3096.00",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "tie",
            "quantity": 10,
            "measurementType": null
        },
        {
            "id": 47,
            "name": "Gembucket",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$2029.36",
            "images": "IMAGE_ARRAY",
            "notes": "tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst",
            "garmentType": "tie",
            "quantity": 100,
            "measurementType": "standard"
        },
        {
            "id": 48,
            "name": "Viva",
            "description": "blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia",
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$1431.97",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "dress shirt",
            "quantity": 25,
            "measurementType": null
        },
        {
            "id": 49,
            "name": "Trippledex",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$5058.22",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "accessories",
            "quantity": 6,
            "measurementType": null
        },
        {
            "id": 50,
            "name": "Ronstring",
            "description": "nisl aenean lectus pellentesque eget nunc donec quis orci eget",
            "canBeAltered": true,
            "canBeShipped": true,
            "price": "$4813.70",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "shoes",
            "quantity": 38,
            "measurementType": null
        },
        {
            "id": 51,
            "name": "Temp",
            "description": "nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet",
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$5038.45",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "slacks",
            "quantity": 10,
            "measurementType": null
        },
        {
            "id": 52,
            "name": "Redhold",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": true,
            "price": "$2995.23",
            "images": "IMAGE_ARRAY",
            "notes": "augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere",
            "garmentType": "sport coat",
            "quantity": 81,
            "measurementType": "custom"
        },
        {
            "id": 53,
            "name": "Asoka",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$1990.26",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "shoes",
            "quantity": 2,
            "measurementType": null
        },
        {
            "id": 54,
            "name": "Opela",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": true,
            "price": "$4604.43",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sportswear",
            "quantity": 72,
            "measurementType": null
        },
        {
            "id": 55,
            "name": "Biodex",
            "description": "proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius",
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$3548.75",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "outerwear",
            "quantity": 72,
            "measurementType": null
        },
        {
            "id": 56,
            "name": "Redhold",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$5494.66",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "dress shirt",
            "quantity": 97,
            "measurementType": null
        },
        {
            "id": 57,
            "name": "Kanlam",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$2445.67",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "suit",
            "quantity": 41,
            "measurementType": null
        },
        {
            "id": 58,
            "name": "Aerified",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$3704.21",
            "images": "IMAGE_ARRAY",
            "notes": "facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla",
            "garmentType": "suit",
            "quantity": 90,
            "measurementType": "standard"
        },
        {
            "id": 59,
            "name": "Zathin",
            "description": "amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in",
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$2660.64",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "outerwear",
            "quantity": 88,
            "measurementType": null
        },
        {
            "id": 60,
            "name": "Ronstring",
            "description": "in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus",
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$5506.55",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "slacks",
            "quantity": 59,
            "measurementType": null
        },
        {
            "id": 61,
            "name": "Duobam",
            "description": "phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl",
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$5060.67",
            "images": "IMAGE_ARRAY",
            "notes": "posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec",
            "garmentType": "sportswear",
            "quantity": 28,
            "measurementType": "custom"
        },
        {
            "id": 62,
            "name": "Flowdesk",
            "description": "sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel",
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$3852.79",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "suit",
            "quantity": 68,
            "measurementType": null
        },
        {
            "id": 63,
            "name": "Stronghold",
            "description": "vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent",
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$4389.99",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "shoes",
            "quantity": 98,
            "measurementType": null
        },
        {
            "id": 64,
            "name": "Viva",
            "description": "sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam",
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$1477.84",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": null,
            "quantity": 44,
            "measurementType": null
        },
        {
            "id": 65,
            "name": "Duobam",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$3324.46",
            "images": "IMAGE_ARRAY",
            "notes": "amet eleifend pede libero quis orci nullam molestie nibh in lectus",
            "garmentType": "accessories",
            "quantity": 20,
            "measurementType": "custom"
        },
        {
            "id": 66,
            "name": "Bitwolf",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$853.05",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sportswear",
            "quantity": 94,
            "measurementType": null
        },
        {
            "id": 67,
            "name": "Kanlam",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$962.61",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": null,
            "quantity": 41,
            "measurementType": null
        },
        {
            "id": 68,
            "name": "Sonsing",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$5429.77",
            "images": "IMAGE_ARRAY",
            "notes": "vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero",
            "garmentType": "tie",
            "quantity": 22,
            "measurementType": "custom"
        },
        {
            "id": 69,
            "name": "Flexidy",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$4086.75",
            "images": "IMAGE_ARRAY",
            "notes": "in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante",
            "garmentType": "tie",
            "quantity": 44,
            "measurementType": "custom"
        },
        {
            "id": 70,
            "name": "Bitchip",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$5393.56",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "shoes",
            "quantity": 96,
            "measurementType": null
        },
        {
            "id": 71,
            "name": "Aerified",
            "description": "nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit",
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$4257.29",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "dress shirt",
            "quantity": 17,
            "measurementType": null
        },
        {
            "id": 72,
            "name": "Redhold",
            "description": "in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget",
            "canBeAltered": true,
            "canBeShipped": true,
            "price": "$709.04",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "formal wear",
            "quantity": 28,
            "measurementType": null
        },
        {
            "id": 73,
            "name": "Duobam",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$5058.94",
            "images": "IMAGE_ARRAY",
            "notes": "cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat",
            "garmentType": "accessories",
            "quantity": 91,
            "measurementType": "standard"
        },
        {
            "id": 74,
            "name": "Voltsillam",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$1760.90",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sportswear",
            "quantity": 34,
            "measurementType": null
        },
        {
            "id": 75,
            "name": "Namfix",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$5069.81",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "formal wear",
            "quantity": 68,
            "measurementType": null
        },
        {
            "id": 76,
            "name": "Temp",
            "description": "eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar",
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$4691.80",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "outerwear",
            "quantity": 91,
            "measurementType": null
        },
        {
            "id": 77,
            "name": "Zathin",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$536.88",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "formal wear",
            "quantity": 33,
            "measurementType": null
        },
        {
            "id": 78,
            "name": "Regrant",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$2750.01",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "shoes",
            "quantity": 55,
            "measurementType": null
        },
        {
            "id": 79,
            "name": "Trippledex",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$2710.11",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sport coat",
            "quantity": 10,
            "measurementType": null
        },
        {
            "id": 80,
            "name": "Stronghold",
            "description": "volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus",
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$3230.43",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "outerwear",
            "quantity": 44,
            "measurementType": null
        },
        {
            "id": 81,
            "name": "Tres-Zap",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": true,
            "price": "$1262.76",
            "images": "IMAGE_ARRAY",
            "notes": "magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum",
            "garmentType": "dress shirt",
            "quantity": 7,
            "measurementType": "custom"
        },
        {
            "id": 82,
            "name": "Stim",
            "description": "vel augue vestibulum ante ipsum primis in faucibus orci luctus",
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$2425.15",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "formal wear",
            "quantity": 81,
            "measurementType": null
        },
        {
            "id": 83,
            "name": "Mat Lam Tam",
            "description": "in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu",
            "canBeAltered": true,
            "canBeShipped": true,
            "price": "$2254.33",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sportswear",
            "quantity": 2,
            "measurementType": null
        },
        {
            "id": 84,
            "name": "Fix San",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$2299.95",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "tie",
            "quantity": 39,
            "measurementType": null
        },
        {
            "id": 85,
            "name": "Y-find",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$1601.29",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sport coat",
            "quantity": 12,
            "measurementType": null
        },
        {
            "id": 86,
            "name": "Tempsoft",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$1076.23",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sportswear",
            "quantity": 46,
            "measurementType": null
        },
        {
            "id": 87,
            "name": "Bytecard",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": true,
            "price": "$1869.19",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sportswear",
            "quantity": 15,
            "measurementType": null
        },
        {
            "id": 88,
            "name": "Fix San",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$3628.42",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sportswear",
            "quantity": 15,
            "measurementType": null
        },
        {
            "id": 89,
            "name": "Fix San",
            "description": "nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis",
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$2365.06",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sportswear",
            "quantity": 81,
            "measurementType": null
        },
        {
            "id": 90,
            "name": "Greenlam",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$2117.42",
            "images": "IMAGE_ARRAY",
            "notes": "lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam",
            "garmentType": "sportswear",
            "quantity": 94,
            "measurementType": "custom"
        },
        {
            "id": 91,
            "name": "Fix San",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$1685.81",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "accessories",
            "quantity": 15,
            "measurementType": null
        },
        {
            "id": 92,
            "name": "Tres-Zap",
            "description": "eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec",
            "canBeAltered": true,
            "canBeShipped": true,
            "price": "$2144.62",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "formal wear",
            "quantity": 99,
            "measurementType": null
        },
        {
            "id": 93,
            "name": "Y-Solowarm",
            "description": "at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue",
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$5443.43",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "dress shirt",
            "quantity": 99,
            "measurementType": null
        },
        {
            "id": 94,
            "name": "Holdlamis",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$552.43",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sport coat",
            "quantity": 53,
            "measurementType": null
        },
        {
            "id": 95,
            "name": "Zontrax",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$988.52",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": null,
            "quantity": 20,
            "measurementType": null
        },
        {
            "id": 96,
            "name": "Job",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$996.60",
            "images": "IMAGE_ARRAY",
            "notes": "sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla",
            "garmentType": "sport coat",
            "quantity": 7,
            "measurementType": "standard"
        },
        {
            "id": 97,
            "name": "Tempsoft",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$2038.03",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "dress shirt",
            "quantity": 33,
            "measurementType": null
        },
        {
            "id": 98,
            "name": "Aerified",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": true,
            "price": "$3518.44",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sport coat",
            "quantity": 42,
            "measurementType": null
        },
        {
            "id": 99,
            "name": "Lotstring",
            "description": "at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis",
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$2186.96",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sportswear",
            "quantity": 77,
            "measurementType": null
        },
        {
            "id": 100,
            "name": "Tres-Zap",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$3670.84",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "outerwear",
            "quantity": 75,
            "measurementType": null
        },
        {
            "id": 101,
            "name": "Voyatouch",
            "description": "gravida nisi at nibh in hac habitasse platea dictumst aliquam",
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$5516.15",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sport coat",
            "quantity": 56,
            "measurementType": null
        },
        {
            "id": 102,
            "name": "Voyatouch",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$2791.51",
            "images": "IMAGE_ARRAY",
            "notes": "nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non",
            "garmentType": "shoes",
            "quantity": 92,
            "measurementType": "standard"
        },
        {
            "id": 103,
            "name": "Fintone",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$5388.46",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "suit",
            "quantity": 19,
            "measurementType": null
        },
        {
            "id": 104,
            "name": "Regrant",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$3412.59",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "dress shirt",
            "quantity": 29,
            "measurementType": null
        },
        {
            "id": 105,
            "name": "Voyatouch",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$2806.03",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "accessories",
            "quantity": 62,
            "measurementType": null
        },
        {
            "id": 106,
            "name": "Flowdesk",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$4302.66",
            "images": "IMAGE_ARRAY",
            "notes": "venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit",
            "garmentType": "accessories",
            "quantity": 82,
            "measurementType": "standard"
        },
        {
            "id": 107,
            "name": "Bytecard",
            "description": "vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien",
            "canBeAltered": true,
            "canBeShipped": true,
            "price": "$1641.84",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "formal wear",
            "quantity": 37,
            "measurementType": null
        },
        {
            "id": 108,
            "name": "Bamity",
            "description": "tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique",
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$3672.41",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": null,
            "quantity": 84,
            "measurementType": null
        },
        {
            "id": 109,
            "name": "Matsoft",
            "description": "vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi",
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$100.52",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "outerwear",
            "quantity": 82,
            "measurementType": null
        },
        {
            "id": 110,
            "name": "Bamity",
            "description": "est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet",
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$908.08",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sport coat",
            "quantity": 45,
            "measurementType": null
        },
        {
            "id": 111,
            "name": "Matsoft",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$4833.44",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "accessories",
            "quantity": 45,
            "measurementType": null
        },
        {
            "id": 112,
            "name": "Cardify",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$1719.87",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "tie",
            "quantity": 28,
            "measurementType": null
        },
        {
            "id": 113,
            "name": "Tres-Zap",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$3923.44",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "formal wear",
            "quantity": 39,
            "measurementType": null
        },
        {
            "id": 114,
            "name": "Redhold",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": true,
            "price": "$5971.13",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "formal wear",
            "quantity": 50,
            "measurementType": null
        },
        {
            "id": 115,
            "name": "Regrant",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$1616.26",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": null,
            "quantity": 98,
            "measurementType": null
        },
        {
            "id": 116,
            "name": "Ronstring",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$662.46",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sportswear",
            "quantity": 55,
            "measurementType": null
        },
        {
            "id": 117,
            "name": "Zaam-Dox",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$604.82",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": null,
            "quantity": 22,
            "measurementType": null
        },
        {
            "id": 118,
            "name": "Zaam-Dox",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$4005.04",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "slacks",
            "quantity": 1,
            "measurementType": null
        },
        {
            "id": 119,
            "name": "Tin",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": true,
            "price": "$2057.60",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "shoes",
            "quantity": 65,
            "measurementType": null
        },
        {
            "id": 120,
            "name": "Zontrax",
            "description": "diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu",
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$546.66",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sport coat",
            "quantity": 67,
            "measurementType": null
        },
        {
            "id": 121,
            "name": "Transcof",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$486.29",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "slacks",
            "quantity": 98,
            "measurementType": null
        },
        {
            "id": 122,
            "name": "Span",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$3189.15",
            "images": "IMAGE_ARRAY",
            "notes": "in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio",
            "garmentType": "suit",
            "quantity": 43,
            "measurementType": "custom"
        },
        {
            "id": 123,
            "name": "Konklab",
            "description": "libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at",
            "canBeAltered": true,
            "canBeShipped": true,
            "price": "$2301.15",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "formal wear",
            "quantity": 60,
            "measurementType": null
        },
        {
            "id": 124,
            "name": "Ventosanzap",
            "description": "tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien",
            "canBeAltered": true,
            "canBeShipped": true,
            "price": "$5016.92",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "accessories",
            "quantity": 13,
            "measurementType": null
        },
        {
            "id": 125,
            "name": "Treeflex",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$1241.81",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sport coat",
            "quantity": 8,
            "measurementType": null
        },
        {
            "id": 126,
            "name": "Kanlam",
            "description": "massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis",
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$4526.85",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sportswear",
            "quantity": 15,
            "measurementType": null
        },
        {
            "id": 127,
            "name": "Zathin",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$2880.95",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sportswear",
            "quantity": 5,
            "measurementType": null
        },
        {
            "id": 128,
            "name": "Pannier",
            "description": "arcu libero rutrum ac lobortis vel dapibus at diam nam",
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$4056.60",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "dress shirt",
            "quantity": 88,
            "measurementType": null
        },
        {
            "id": 129,
            "name": "Cookley",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$539.61",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "shoes",
            "quantity": 3,
            "measurementType": null
        },
        {
            "id": 130,
            "name": "Toughjoyfax",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$1590.15",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sportswear",
            "quantity": 17,
            "measurementType": null
        },
        {
            "id": 131,
            "name": "Fintone",
            "description": "scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus",
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$996.32",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "outerwear",
            "quantity": 7,
            "measurementType": null
        },
        {
            "id": 132,
            "name": "Zoolab",
            "description": "et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium",
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$5905.42",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sport coat",
            "quantity": 58,
            "measurementType": null
        },
        {
            "id": 133,
            "name": "Alpha",
            "description": "morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis",
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$664.02",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "accessories",
            "quantity": 62,
            "measurementType": null
        },
        {
            "id": 134,
            "name": "Alphazap",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$3821.84",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sport coat",
            "quantity": 50,
            "measurementType": null
        },
        {
            "id": 135,
            "name": "Stronghold",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$1173.17",
            "images": "IMAGE_ARRAY",
            "notes": "nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit",
            "garmentType": "accessories",
            "quantity": 79,
            "measurementType": "standard"
        },
        {
            "id": 136,
            "name": "Sonair",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$2975.44",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": null,
            "quantity": 29,
            "measurementType": null
        },
        {
            "id": 137,
            "name": "Daltfresh",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$5983.56",
            "images": "IMAGE_ARRAY",
            "notes": "sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis",
            "garmentType": "sport coat",
            "quantity": 20,
            "measurementType": "standard"
        },
        {
            "id": 138,
            "name": "Gembucket",
            "description": "aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien",
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$5920.84",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "shoes",
            "quantity": 5,
            "measurementType": null
        },
        {
            "id": 139,
            "name": "Stronghold",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$3667.99",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "suit",
            "quantity": 41,
            "measurementType": null
        },
        {
            "id": 140,
            "name": "Span",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": true,
            "price": "$672.99",
            "images": "IMAGE_ARRAY",
            "notes": "luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti",
            "garmentType": "formal wear",
            "quantity": 40,
            "measurementType": "standard"
        },
        {
            "id": 141,
            "name": "Treeflex",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$4155.42",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "dress shirt",
            "quantity": 55,
            "measurementType": null
        },
        {
            "id": 142,
            "name": "Home Ing",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$3323.00",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "outerwear",
            "quantity": 1,
            "measurementType": null
        },
        {
            "id": 143,
            "name": "Cardguard",
            "description": "justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem",
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$2028.30",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sport coat",
            "quantity": 85,
            "measurementType": null
        },
        {
            "id": 144,
            "name": "Stim",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$5511.77",
            "images": "IMAGE_ARRAY",
            "notes": "elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu",
            "garmentType": "formal wear",
            "quantity": 67,
            "measurementType": "standard"
        },
        {
            "id": 145,
            "name": "Biodex",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": true,
            "price": "$4007.66",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "accessories",
            "quantity": 16,
            "measurementType": null
        },
        {
            "id": 146,
            "name": "Redhold",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$2298.60",
            "images": "IMAGE_ARRAY",
            "notes": "vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus",
            "garmentType": "shoes",
            "quantity": 76,
            "measurementType": "standard"
        },
        {
            "id": 147,
            "name": "Redhold",
            "description": null,
            "canBeAltered": true,
            "canBeShipped": false,
            "price": "$900.09",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "dress shirt",
            "quantity": 3,
            "measurementType": null
        },
        {
            "id": 148,
            "name": "Solarbreeze",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$3897.31",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sportswear",
            "quantity": 33,
            "measurementType": null
        },
        {
            "id": 149,
            "name": "Fixflex",
            "description": null,
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$5164.71",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "accessories",
            "quantity": 13,
            "measurementType": null
        },
        {
            "id": 150,
            "name": "Span",
            "description": "pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac",
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$5290.22",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": null,
            "quantity": 52,
            "measurementType": null
        },
        {
            "id": 151,
            "name": "Y-find",
            "description": "lobortis ligula sit amet eleifend pede libero quis orci nullam molestie",
            "canBeAltered": false,
            "canBeShipped": false,
            "price": "$4040.99",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "sport coat",
            "quantity": 48,
            "measurementType": null
        },
        {
            "id": 1000,
            "name": "Voltsillam",
            "description": "est risus auctor sed tristique in tempus sit amet sem fusce consequat",
            "canBeAltered": false,
            "canBeShipped": true,
            "price": "$3107.53",
            "images": "IMAGE_ARRAY",
            "notes": null,
            "garmentType": "suit",
            "quantity": 46,
            "measurementType": null
        }],
    orders: [
         {
            "id": 0,
            "customerId": 3,
            "dateOfOrder": 1497685810386,
            "images": [],
            "isOpen": true,
            "orderItems": {
                321: {
                    "id": 11,
                    "name": "Fix San",
                    "description": null,
                    "canBeAltered": true,
                    "canBeShipped": true,
                    "price": "$4131.56",
                    "images": "IMAGE_ARRAY",
                    "notes": null,
                    "garmentType": "sportswear",
                    "quantity": 16,
                    "measurementType": null
                },
                123: {
                    "id": 7,
                    "name": "Latlux",
                    "description": null,
                    "canBeAltered": false,
                    "canBeShipped": false,
                    "price": "$1001.58",
                    "images": "IMAGE_ARRAY",
                    "notes": null,
                    "garmentType": "dress shirt",
                    "quantity": 85,
                    "measurementType": null
                }
            },
            "notes": null,
            "orderTotal": null,
            "owner": "gabe boley",
            "status": "open"
        }
    ],
    page: 'create-order'
}
