export const ADD_ITEM = 'ADD_ITEM';
export const CREATE_NEW = 'CREATE_NEW';
export const REVIEW_ORDER = 'REVIEW_ORDER';
export const CONFIRM_CUSTOMER = 'CONFIRM_CUSTOMER';
export const CUSTOMER_SELECTION = 'CUSTOMER_SELECTION';
export const EXISTING_SELECTION = 'EXISTING_SELECTION';
export const CREATE_CUSTOMER_GUEST = 'CREATE_CUSTOMER_GUEST';
